name: kamus3bahasa
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.5.1
  get_cli: ^1.6.0
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  hexcolor: ^2.0.5
  lottie: ^1.2.1
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/json/kamus.json
    - assets/json/kalimat.json
    - assets/images/logo.png
    - assets/images/conversations.png
  uses-material-design: true
